### ISSUE TITLE
EPIC: GraphQL integration

### ISSUE THREAD

**Issue by Maverick17user** [Compoundfolio/investing-root#78]
### Front-end scope:
- [x] Configure generating TypeScpript types from SDL: https://api.compoundfolio.com/graphql/sdl
- [x] Find GraphQL client library for frontend (may be integrated with ⤴ 
- [x] Refactor `Api.POST` to be able to work with gql **queries**
- [x] Refactor `Api.POST` to be able to work with gql **mutations**
- [ ] Implement basic optimistic update stratagies
- [ ] Add proper error handling mechanism
- [x] Abstract react-query `useQuery` & `useMutation` hooks
- [ ] On page reload (or initial load) app should select recently selected portfolio automatically 
- [ ] Think about how to organize `/services` folder (with all the gql. request stuff inside)
- [ ] Think about how to output **error messages** (custom toasts?)
- [ ] Think about how to output **loading statuses** (custom toasts?)
- [ ] Integrate gql for **portfolios CRUD logic**
- [ ] Integrate gql for portfolio **transactions CRUD logic**
- [ ] Integrate gql for portfolio **transactions file upload logic**

### Weird stuff noticed
- [ ] `DISCUSSION NEEDED` @alexesmet I had a pretty old token saved in localStorage. I used it to make the query. Api gave me the response that I'm not **Authorized**. I've fixed it by cleaning up the localStorage, and re-auth, and it started to allow me to make requests. What if it will happen once again? We need to think about how to handle it.

### Back-end scope:
- [x] Publish the GraphQL: https://api.compoundfolio.com/graphql
- [x] Publish the SDL file: https://api.compoundfolio.com/graphql/sdl
- [x] Make integration instructions: https://youtu.be/DLkYhVG0ONM

**Comment by alexesmet** [comment]
@Maverick17user 

While I can't choose the graphql client for you (as I already heard you have an opinion on Apollo Client), [there is a list of other graphql clients](https://graphql.org/code/#javascript-client) that you should go through and pick, as you will be the one who works with it the most.

Just keep in mind that you will **massively** benefit from using a client that is capable of parsing SLD (graphql schema) file. It will provide in-editor highlighting, syntax checking and API documentation.

**Comment by alexesmet** [comment]
## Uploading a file through graphql API

File is uploaded through a formdata. Full cURL example:

```sh
curl -w "\nTotal time: %{time_total}s\n" --show-error -D - \
    -X POST api.dev.compoundfolio/graphql \
    -H "Authorization: Bearer $TOKEN" \
    --form 'operations={"query": "mutation UploadFile($file: Upload!) { uploadReport(brokerage: EXANTE, portfolioId: \"d5bd66bb-d8fb-4da2-849e-5af7593a35ba\", upload: $file) { id, fiscalTransactions, tradeOperations} }", "variables": { "file": null } }'  \
    --form 'map={ "nFile": ["variables.file"] }' \
    --form nFile=@testdata/exante_small_report.csv
```

### Explanation:
You make a `POST` request to `https://api.dev.compoundfolio/graphql` , and then provide 3 form data entries:
- `operations` as a GraphQL query string
- `map` to connect the file from GraphQL query to an other piece of form data
- `nFile` is linked to file upload HTML element
Don't forget to provide auth header.

### Axios example
```js
const form = new FormData();
form.append('my_field', 'my value');
form.append('my_buffer', new Blob([1,2,3]));
form.append('my_file', fileInput.files[0]);

axios.post('https://example.com', form)
```
However, you will most likely be using a graphql lib, so your code will be different.

**Comment by Maverick17user** [comment]
@alexesmet 

Cool news - looks like gql.tada package is our solution for the front-end part of gql integration!

I've been able to friend it with `react-query` 🙌

Extended my task-list, moving forward!

**Comment by Maverick17user** [comment]
Done core functionality closed.

Other stuff passed to separate cards which will be discussed first!
